version: '3.7'

services:
  app-server:
    build: .
    ports:
      - "10222:10222"
    depends_on: 
      - db 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/veh_manager?useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: root     
    networks: 
      - backend
      - frontend
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'veh_manager'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  

volumes:
  db-data:

networks:
  backend:
  frontend:    